package opencode

import (
	"os"
	"path/filepath"
	"strings"
)

// opencode's built-in websearch tool posts to https://search.parallel.ai/mcp or
// https://mcp.exa.ai/mcp from opencode's own runtime, and it only reaches the
// model when the provider is opencode's own or one of the OPENCODE_ENABLE_*
// flags is set. Prizmal leaves those flags alone, denies the built-in tool
// outright, and ships its own search tool that goes through the Switch.
//
// opencode has no config key that declares a tool inline, so the tool has to be
// a file: its registry globs `{tool,tools}/*.{js,ts}` across the config
// directories. OPENCODE_CONFIG_DIR adds one directory to that list, which lets
// prizmal keep the file in its own cache rather than in the user's opencode
// config. Unsetting the variable takes the tool back out.
const (
	// openCodeSearchToolID is both the file's basename and the tool name the
	// model sees, because opencode derives the id from the filename. It must
	// not be "websearch": the registry drops every tool with that id, custom
	// ones included, whenever the provider is not opencode's own.
	openCodeSearchToolID = "prizmal_search"

	// The generated tool reads its target and credential from these variables
	// at call time, so nothing secret is written to disk.
	openCodeSearchURLEnv   = "PRIZMAL_OPENCODE_SEARCH_URL"
	openCodeSearchKeyEnv   = "PRIZMAL_OPENCODE_SEARCH_KEY"
	openCodeSearchModelEnv = "PRIZMAL_OPENCODE_SEARCH_MODEL"
)

// openCodeSearchDir returns the prizmal-owned directory handed to opencode as
// OPENCODE_CONFIG_DIR.
func openCodeSearchDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".cache", "prizmal", "opencode"), nil
}

// writeOpenCodeSearchTool generates the search tool under dir/tool. The file is
// rewritten on every launch so an older prizmal's version never lingers.
func writeOpenCodeSearchTool(dir string) error {
	toolDir := filepath.Join(dir, "tool")
	if err := os.MkdirAll(toolDir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(toolDir, openCodeSearchToolID+".ts")
	return os.WriteFile(path, []byte(openCodeSearchToolSource()), 0o644)
}

// openCodeSearchToolSource renders the tool module. opencode recognises a tool
// by shape alone (an object carrying description, args and execute), so the
// module imports nothing and runs before the background dependency install
// opencode kicks off for each config directory has finished.
//
// `args` entries are plain JSON Schema fragments, which is the path opencode's
// registry takes when the values are not Zod types. Every declared arg is
// marked required, so the tool declares exactly one.
func openCodeSearchToolSource() string {
	return strings.NewReplacer(
		"__URL_ENV__", openCodeSearchURLEnv,
		"__KEY_ENV__", openCodeSearchKeyEnv,
		"__MODEL_ENV__", openCodeSearchModelEnv,
	).Replace(openCodeSearchToolTemplate)
}

const openCodeSearchToolTemplate = `// Generated by prizmal on launch. Edits are overwritten.
//
// Routes web search through PrizmalSwitch, so an opencode session needs no
// opencode account and makes no call to opencode's hosted search backends.
// The Switch host, key and model arrive in the process environment.

function collectText(payload) {
  if (!payload || typeof payload !== "object") return ""
  if (typeof payload.output_text === "string" && payload.output_text) return payload.output_text
  const parts = []
  for (const item of Array.isArray(payload.output) ? payload.output : []) {
    for (const chunk of Array.isArray(item && item.content) ? item.content : []) {
      if (chunk && typeof chunk.text === "string" && chunk.text) parts.push(chunk.text)
    }
  }
  return parts.join("\n\n")
}

export default {
  description:
    "Search the web through PrizmalSwitch. Returns a summary of current sources with their URLs. " +
    "Use it for anything that postdates the model's training data, or that needs a citable source.",
  args: {
    query: { type: "string", description: "What to search the web for." },
  },
  async execute(args, ctx) {
    const base = (process.env.__URL_ENV__ || "").replace(/\/+$/, "")
    if (!base) {
      throw new Error("prizmal search is unconfigured: __URL_ENV__ is unset. Relaunch through the prizmal CLI.")
    }
    const key = process.env.__KEY_ENV__ || ""
    const model = process.env.__MODEL_ENV__ || ""

    const headers = { "content-type": "application/json" }
    if (key) headers["authorization"] = "Bearer " + key

    const response = await fetch(base + "/responses", {
      method: "POST",
      headers,
      signal: ctx && ctx.abort,
      body: JSON.stringify({
        model,
        tools: [{ type: "web_search" }],
        input:
          "Search the web and answer with a short factual summary followed by the source URLs.\n\nQuery: " +
          args.query,
      }),
    })

    if (!response.ok) {
      let detail = ""
      try {
        detail = (await response.text()).slice(0, 500)
      } catch {}
      throw new Error(
        "prizmal search: the Switch answered " +
          response.status +
          " on /responses. Server-side web search may not be available on this tenant yet." +
          (detail ? " Response: " + detail : ""),
      )
    }

    const output = collectText(await response.json())
    return {
      title: "Prizmal search: " + args.query,
      output: output || "No results for that query.",
      metadata: { model },
    }
  },
}
`

// filterEnv returns env without any entry whose prefix matches name, so an
// appended replacement is unconditional rather than relying on the exec
// last-occurrence convention for duplicate environment entries.
func filterEnv(env []string, prefix string) []string {
	out := env[:0:0]
	for _, kv := range env {
		if strings.HasPrefix(kv, prefix) {
			continue
		}
		out = append(out, kv)
	}
	return out
}
